version: "3.7"

services:
  ubuntu:
    # image: "ubuntu:18.04-dev"
    build: .
    volumes:
      - ./:/root/dev
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  
  deno:
    # image: "deno-docker:0.0.1-api"
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
        - ./api:/app
    ports:
      - "7777:8000"
    networks: 
      - deno

  react:
    # image: "react"
    build:
      context: ./app
      dockerfile: Dockerfile
    # depends_on:
    #   - api
    #   - api_demo
    volumes:
      - ./app/:/app/
      - /app/node_modules/
    restart: always
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=development
    networks:
      - deno

  mariadb:
    image: mariadb
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example #root password
      # MYSQL_USER, MYSQL_PASSWORD
      # MYSQL_DATABASE
      # MYSQL_ALLOW_EMPTY_PASSWORD
      # MYSQL_RANDOM_ROOT_PASSWORD
    networks:
      - deno

networks:
  deno: {}

# web server? 
#   proxy:
#     image: nginx:1.17-alpine
#     container_name: reverse-proxy
#     depends_on:
#       - design
#       - api
#       - api_demo
#     volumes:
#       - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
#     restart: always
#     ports:
#       - "80:80"
#     networks:
#       - webnet
